apiVersion: controller-runtime.sigs.k8s.io/v1alpha1
kind: ControllerManagerConfig
# the configuration of controller-manager, which configs the health probe address, metrics address, webhook address, and enabling leader election or not
health:
  healthProbeBindAddress: :8081
metrics:
  bindAddress: 127.0.0.1:8080
webhook:
  port: 9443
leaderElection:
  leaderElect: true
  resourceName: 24a4cdb8.hliangzhao.io
