resources:
  - manager.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  # manager-config is a Volume (ConfigMap) for updating the config of controller-manager
  - files:
      - controller_manager_config.yaml
    name: manager-config
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
  - name: controller
    # `controller` will be replaced by `docker.io/hliangzhao97/balancer:latest`
    newName: docker.io/hliangzhao97/balancer
    newTag: latest
