apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  # bind the Role leader-election-role with controller-manager, which gives controller-manager the ability of leader election
  name: leader-election-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: leader-election-role
subjects:
  - kind: ServiceAccount
    name: controller-manager
    namespace: system
