// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/hliangzhao/balancer/pkg/client/clientset/versioned/typed/balancer/v1alpha1"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeHliangzhaoV1alpha1 struct {
	*testing.Fake
}

func (c *FakeHliangzhaoV1alpha1) Balancers(namespace string) v1alpha1.BalancerInterface {
	return &FakeBalancers{c, namespace}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeHliangzhaoV1alpha1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
