// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// BalancerListerExpansion allows custom methods to be added to
// BalancerLister.
type BalancerListerExpansion interface{}

// BalancerNamespaceListerExpansion allows custom methods to be added to
// BalancerNamespaceLister.
type BalancerNamespaceListerExpansion interface{}
